name: php-tester
version: '1.5.4'
summary: A simple tool to run your PHP scribbles. 
description: |
  A Vala application to test PHP snippets without having to start a server. 

icon: snap/gui/php-tester.png
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
    php-tester:
        command: com.github.bartzaalberg.php-tester
        desktop: usr/share/applications/com.github.bartzaalberg.php-tester.desktop
        plugs: [home, x11, unity7, gsettings]

parts:
    granite:
        plugin: cmake
        source: lp:granite/0.4
        source-type: bzr
        configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/usr, -DCMAKE_INSTALL_LIBDIR=/usr/lib]
        build-packages:
          - build-essential
          - valac
        stage-packages:
          - valac-0.30-vapi

    php-tester:
        after: [granite, desktop-gtk3]
        source: https://github.com/bartzaalberg/php-tester.git
        plugin: cmake        
        configflags: [-DCMAKE_INSTALL_PREFIX=/usr]
        build-packages:
            - build-essential
            - valac
            - intltool
            - libgee-0.8-dev
            - debhelper
            - libgtk-3-dev
            - libgranite-dev
            - libgtksourceview-3.0-dev
        stage-packages:
            - gnome-keyring
            - gobject-introspection
            - libgdk-pixbuf2.0-0
            - libgee-0.8-2
            - libgtk-3-0
